[1mdiff --git a/Data Access/src/main/java/ra/inge/ucr/da/Data.java b/Data Access/src/main/java/ra/inge/ucr/da/Data.java[m
[1mindex 50cc351..0f8fb1b 100644[m
[1m--- a/Data Access/src/main/java/ra/inge/ucr/da/Data.java[m	
[1m+++ b/Data Access/src/main/java/ra/inge/ucr/da/Data.java[m	
[36m@@ -48,7 +48,7 @@[m [mpublic class Data {[m
         add(new TargetObject(29, TargetType.MONUMENT, 9.936614, -84.050735, 0, "Escultura 'Antárticos'", "antarticos", "Escultura hecha en acero doblado y pintado.", "VideoPlayback/antarticos.mp4", "http://www.miucr.ucr.ac.cr/", R.drawable.antarticos));[m
         add(new TargetObject(30, TargetType.MONUMENT, 9.936614, -84.050735, 0, "Escultura 'Osos Amorosos'", "osos_amorosos", "Escultura  hecha en mármol blanco, en 1992, por el escultor José Sancho.", "VideoPlayback/osos.mp4", "http://www.miucr.ucr.ac.cr/", R.drawable.osos_amorosos));[m
         add(new TargetObject(31, TargetType.MONUMENT, 9.936614, -84.050735, 0, "Leda y el Cisne", "leda", "Monumento formado por granito de escazú, esculpido por el reconocido José Sancho en 1980", "VideoPlayback/leda.mp4", "http://www.miucr.ucr.ac.cr/", R.drawable.leda));[m
[31m-        add(new TargetObject(32, TargetType.MONUMENT, 9.936614, -84.050735, 0, "Busto de José Joaquín Gutiérrez", "bustos", "Decano de la Facultad de Cirugía Dental de la UCR y primer odontólogo de América Latina.", "VideoPlayback/joaquin.mp4", "http://www.miucr.ucr.ac.cr/", R.drawable.jose));[m
[32m+[m[32m        add(new TargetObject(32, TargetType.MONUMENT, 9.936614, -84.050735, 0, "Busto de José Joaquín Gutiérrez", "busto", "Decano de la Facultad de Cirugía Dental de la UCR y primer odontólogo de América Latina.", "VideoPlayback/joaquin.mp4", "http://www.miucr.ucr.ac.cr/", R.drawable.jose));[m
         add(new TargetObject(33, TargetType.MONUMENT, 9.936614, -84.050735, 0, "Licenciado Fernando Bauza", "fernando", "Decano de la Facultad de Derecho en 1939 y rector de la Universidad de Costa Rica por primera vez en 1946.", "VideoPlayback/fernando.mp4", "http://www.miucr.ucr.ac.cr/", R.drawable.fernando_baudrit));[m
         add(new TargetObject(34, TargetType.MONUMENT, 9.936244, -84.050692, 0, "Plaza 24 de abril", "plaza24", "En 1971, la FEUCR decidió bautizar y colocar una placa conmemorativa de  la gesta de ALCOA en   la UCR y en ella, escrita en mármol se grabó. “A la juventud de Costa Rica, Plaza 24 de Abril, violar la ley del imperio es defender los derechos del pueblo”.", "VideoPlayback/24-abril.mp4", "http://www.miucr.ucr.ac.cr/", R.drawable.plaza24));[m
         add(new TargetObject(35, TargetType.MONUMENT, 9.935895, -84.050638, 0, "El Pretil", "pretil", "Fofidescripcion", "VideoPlayback/antarticos.mp4", "http://www.miucr.ucr.ac.cr/", R.drawable.pretil));[m
